### ISSUE TITLE
Create Component Architecture

### ISSUE THREAD

**Issue by reesegreen2014** [reesegreen2014/dog-info-hub#3]
### Description:
Define and create the component architecture for the project in VS Code. This task involves setting up the folder structure and creating initial component files for each main page of the application.

### Tasks

- [x] Create `components` folder
- [x] Create `Home Page` folder and files `HomePage.js` and `HomePage.css`
- [x] Create `Quiz Page` folder and files `QuizPage.js` and `QuizPage.css`
- [x] Create `All Breeds` folder and files `AllBreeds.js` and `AllBreeds.css`
- [x] Create `Breed Details` folder and files `BreedDetails.js` and `BreedDetails.css`
- [x] Create `My Favorites` folder and files `MyFavorites.js` and `MyFavorites.css`
- [x] Create `Pet Owner Resources` folder and files `PetOwnerResources.js` and `PetOwnerResources.css`
- [x] Create `Header` folder and files `Header.js` and `Header.css`
- [x] Create `Footer` folder and files `Footer.js` and `Footer.css`
